[container.image]
repository="ramilu90"
name="content_based_routing"
tag="1.0.6"

# -----------------------------------------------------------------------
# ConfigMap: ballerina-values-content-based-routing
# Fund recipient URLs + routing thresholds
# -----------------------------------------------------------------------
[[cloud.config.envs]]
key_ref="afaRecipientUrl"
config_name="ballerina-values-content-based-routing"

[[cloud.config.envs]]
key_ref="alfaRecipientUrl"
config_name="ballerina-values-content-based-routing"

[[cloud.config.envs]]
key_ref="folksamRecipientUrl"
config_name="ballerina-values-content-based-routing"

[[cloud.config.envs]]
key_ref="highValueThresholdStr"
config_name="ballerina-values-content-based-routing"

[[cloud.config.envs]]
key_ref="BAL_CONFIG_DATA"
config_name="ballerina-values-content-based-routing"
