[package]
org = "ramindu"
name = "store_and_forward_integration"
version = "0.1.0"
distribution = "2201.13.1"
title = "store_and_forward_integration"

[build-options]
cloud = "k8s"
remoteManagement = true
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "rabbitmq"
version = "3.1.0"
