apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
  labels:
    k8s-app: kube-dns
data:
  wso2.server: |
    wso2.com:53 {
        errors
        cache 30
        hosts {
            # Point EVERYTHING to the Nginx Ingress Controller IP (10.0.7.22)
            10.0.7.22 is.wso2.com
            10.0.7.22 cp.wso2.com
            10.0.7.22 gw.wso2.com
            10.0.7.22 icp.wso2.com
            10.0.7.22 extgw.wso2.com
            10.0.7.22 kibana.wso2.com
            10.0.7.22 rabbitmq.wso2.com
            
            fallthrough
        }
        forward . 8.8.8.8 1.1.1.1 
        reload
    }
