apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
  labels:
    k8s-app: kube-dns
data:
  wso2.server: |
    wso2.com:53 {
        errors
        cache 30
        hosts {
            # Point EVERYTHING to the Nginx Ingress Controller IP (10.43.234.238)
            10.43.234.238 is.wso2.com
            10.43.234.238 cp.wso2.com
            10.43.234.238 gw.wso2.com
            10.43.234.238 icp.wso2.com
            10.43.234.238 extgw.wso2.com
            10.43.234.238 kibana.wso2.com
            10.43.234.238 rabbitmq.wso2.com
            
            fallthrough
        }
        forward . 8.8.8.8 1.1.1.1 
        reload
    }
