[package]
org = "ramindu"
name = "parallel_service_ochastration_integration"
version = "0.1.0"
title = "parallel_service_ochastration_integration"

[build-options]
cloud = "k8s"
remoteManagement=true
observabilityIncluded=true
