apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
  labels:
    k8s-app: kube-dns
data:
  wso2.server: |
    airline.wso2.com:53 {
        errors
        cache 30
        hosts {
            192.168.1.21 cp.airline.wso2.com gw.airline.wso2.com kibana.airline.wso2.com
            fallthrough
        }
    }