name: WSO2 API CI/CD - Prod- Airline Pipeline
on:
  push:
    paths:
      - 'apim/AirlineProductAPI/**'
      - '.github/workflows/airline-api-pipeline.yml'
    branches:
      - prod

jobs:
  deploy-api-prod:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'prod') || github.event_name == 'push' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add etc/hosts entry for airbus.am.wso2.com 🌐
        run: |
          echo '135.235.250.243 airbus.am.wso2.com' | sudo tee -a /etc/hosts

      - name: Install apictl
        run: |
          wget https://github.com/wso2/product-apim-tooling/releases/download/v4.6.0/apictl-4.6.0-linux-amd64.tar.gz
          tar -xzf apictl-4.6.0-linux-amd64.tar.gz
          chmod +x apictl/apictl
          sudo mv apictl/apictl /usr/local/bin/

      - name: Add Prod Environment
        run: |
          apictl add env prod --apim https://${{ secrets.WSO2_APIM }}

      - name: Login to Prod
        run: |
          apictl login prod -u ${{ secrets.APIM_USERNAME }} -p ${{ secrets.APIM_PASSWORD }} --insecure

      # -------------------------------------------------------------
      # NEW STEP: Check Existence
      # -------------------------------------------------------------
      - name: Check if API Exists in Prod
        id: check_api
        run: |
          # Query for the API by name (ensure this matches the name in api.yaml)
          # Assuming API Name is 'AirlineProductAPI'
          EXISTING_API=$(apictl get apis -e prod -q name:AirlineProductAPI --insecure --format json | jq -r '.count')
          
          if [ "$EXISTING_API" -gt "0" ]; then
            echo "API found. A new revision will be created."
            echo "api_exists=true" >> $GITHUB_OUTPUT
          else
            echo "API not found. A new API will be created."
            echo "api_exists=false" >> $GITHUB_OUTPUT
          fi

      # -------------------------------------------------------------
      # MODIFIED STEP: Import with logic logging
      # -------------------------------------------------------------
      - name: Import API to Prod
        run: |
          if [ "${{ steps.check_api.outputs.api_exists }}" == "true" ]; then
             echo "🚀 Updating existing API and creating a new Revision..."
          else
             echo "🆕 Creating fresh API..."
          fi

          # The --update flag is crucial here. 
          # It tells WSO2: "If exists, create new revision. If not, create new API."
          apictl import api -f apim/AirlineProductAPI/ -e prod --preserve-provider=false --update --insecure 

      - name: Run Tests (Optional)
        run: |
          found=false
          # Loop 3 times
          for i in {1..3}; do
            echo "Attempt $i: Checking for org1API..."
            
            # -q means quiet mode (don't output the line, just return true/false)
            if apictl get apis -e prod --insecure | grep -q "org1API"; then
              echo "✅ org1API is present in Publisher (prod)"
              found=true
              break
            fi
            
            echo "⚠️ API not found yet. Waiting 2 seconds..."
            sleep 2
          done

          # Final check
          if [ "$found" = false ]; then
            echo "❌ org1API not found in Publisher (prod) after 3 attempts."
            # List all APIs to see what IS there (helps debugging)
            echo "Available APIs were:"
            apictl get apis -e prod --insecure
            exit 1
          fi