# for arm64 architecture
FROM ramilu90/wso2am-uni-gw-arm:4.6.0
COPY mysql-connector-j-8.4.0.jar /home/wso2carbon/wso2am-universal-gw-4.6.0/repository/components/lib/

# for amd64 architecture
# FROM docker.wso2.com/wso2am-universal-gw:4.6.0.10
# COPY mysql-connector-j-8.4.0.jar /home/wso2carbon/wso2am-universal-gw-4.6.0/repository/components/lib/