#!/bin/bash
set -e

NAMESPACE="ballerina"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

echo "================================================"
echo "  Deploy insurance_backend (arm64)"
echo "================================================"

echo ""
echo "--- Building Ballerina project ---"
cd "$SCRIPT_DIR"
/Users/ramindu/Downloads/ballerina-2201.13.2/bin/bal clean
/Users/ramindu/Downloads/ballerina-2201.13.2/bin/bal build

# Derive image name/tag from what the build just produced
IMAGE=$(grep 'image:' "$SCRIPT_DIR/target/kubernetes/insurance_backend/insurance_backend.yaml" | head -1 | awk '{print $2}' | tr -d '"')

echo ""
echo "--- Docker login ---"
docker login

echo ""
echo "--- Build arm64 image & push ($IMAGE) ---"
docker build \
  -t "$IMAGE" \
  "$SCRIPT_DIR/target/docker/insurance_backend/"

docker push "$IMAGE"

echo ""
echo "--- Applying ConfigMap ---"
kubectl apply -f "$SCRIPT_DIR/config-map-insurance_backend.yaml" -n "$NAMESPACE"

echo ""
echo "--- Applying Deployment and HPA (generated by bal build) ---"
kubectl apply -f "$SCRIPT_DIR/target/kubernetes/insurance_backend/insurance_backend.yaml" -n "$NAMESPACE"

echo ""
echo "--- Setting HPA maxReplicas to 1 ---"
kubectl patch hpa insurance-backe -n "$NAMESPACE" --patch '{"spec":{"maxReplicas":1}}'

echo ""
echo "--- Applying Services ---"
kubectl apply -n "$NAMESPACE" -f - <<EOF
apiVersion: v1
kind: Service
metadata:
  labels:
    app: insurance_backend
  name: insurance-backend-svc
  namespace: $NAMESPACE
spec:
  ports:
  - name: customer-port
    port: 8082
    protocol: TCP
    targetPort: 8082
  - name: agent-port
    port: 8083
    protocol: TCP
    targetPort: 8083
  selector:
    app: insurance_backend
EOF

echo ""
echo "--- Restarting deployment to pick up changes ---"
kubectl rollout restart deployment/insurance-backe-deployment -n "$NAMESPACE"
kubectl rollout status deployment/insurance-backe-deployment -n "$NAMESPACE" --timeout=120s

echo ""
echo "================================================"
echo "  Done! Namespace: $NAMESPACE"
echo ""
echo "  Insurance backend:"
echo "    Customer API: port 8082"
echo "    Agent API:    port 8083"
echo "================================================"
